services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"  # Edge Agent
      - "9443:9443"  # Web UI (HTTPS)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Manage local Docker
      - portainer_data:/data
    networks:
      - portainer_net

volumes:
  portainer_data:

networks:
  portainer_net:
    driver: bridge
